{
    "name": "DATEV Cloud Connector - Payroll",
    "version": "17.0.1.1.1",
    "category": "Human Resources/Payroll",
    "summary": "Export payroll and HR data from Odoo to DATEV LODAS / Lohn und Gehalt",
    "author": "Aquarius Ventures",
    "website": "https://github.com/aquarius-ventures/odoo-datev-connector",
    "license": "LGPL-3",
    "depends": ["datev_connector", "datev_connector_hr", "hr", "hr_payroll"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/datev_salary_type_views.xml",
        "views/datev_payroll_run_views.xml",
        "views/datev_employee_mapping_views.xml",
        "views/datev_payroll_export_views.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/datev_payroll_demo.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
